### ISSUE TITLE
Unable to ad-hoc package for iOS

### ISSUE THREAD

**Issue by 62316e** [away3d/awayphysics-core-fp11#16]
I'm using: Adobe Air 3.8 Asc 2 or (Flex 3.7 without asc2) and ad-hoc build fails with error

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
at adobe.abc.GlobalOptimizer.createBlock(GlobalOptimizer.java:9952)
at adobe.abc.GlobalOptimizer.merge(GlobalOptimizer.java:9984)
at adobe.abc.GlobalOptimizer$InputAbc.readCode(GlobalOptimizer.java:1265
)
at adobe.abc.GlobalOptimizer$InputAbc.readBody(GlobalOptimizer.java:685)

at adobe.abc.GlobalOptimizer$InputAbc.readBodies(GlobalOptimizer.java:40
4)
at adobe.abc.LLVMEmitter.generateBitcode(LLVMEmitter.java:331)
at com.adobe.air.ipa.AOTCompiler.convertAbcToLlvmBitcodeImpl(AOTCompiler
.java:611)
at com.adobe.air.ipa.BitcodeGenerator.main(BitcodeGenerator.java:104)
Compilation failed while executing : ADT

APK setup creation FAILED.
```

**Comment by 62316e** [comment]
Any news?

**Comment by muzerly** [comment]
How much is your computer memory capacity?

**Comment by 62316e** [comment]
I have 10 different pc with 4-16gb ram. This is not related to memory .
Ive created issue on stackoveflow please read. It
